name: Twitch2MinecraftChat
version: @version@
main: com.github.marcusronnback.twitch2minecraftchat.Main
api-version: 1.16
commands:
  start:
    usage: /tmc:start
    description: Start the twitch chat bot
    aliases: [tmcson]
  stop:
    usage: /tmc:stop
    description: Stop the twitch chat bot
    aliases: [tmcsoff]
  togglechat:
    usage: /tmc:togglechat
    description: Enable/Disable Twitch chat
    aliases: [tmctoggle]

